# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'translator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for translator

	pod 'Google-Mobile-Ads-SDK'

  target 'translatorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'translatorUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
